#ifndef __MSI_EC_CONSTANTS__
#define __MSI_EC_CONSTANTS__

#define MSI_DRIVER_NAME "msi-ec"
#define MSI_EC_WEBCAM_ADDRESS 0x2e
#define MSI_EC_WEBCAM_ON 0x4a
#define MSI_EC_WEBCAM_OFF 0x48
#define MSI_EC_FN_WIN_ADDRESS 0xbf
#define MSI_EC_FN_KEY_LEFT 0x40
#define MSI_EC_FN_KEY_RIGHT 0x50
#define MSI_EC_WIN_KEY_LEFT 0x50
#define MSI_EC_WIN_KEY_RIGHT 0x40
#define MSI_EC_BATTERY_MODE_ADDRESS 0xef
#define MSI_EC_BATTERY_MODE_MAX_CHARGE 0xe4
#define MSI_EC_BATTERY_MODE_MEDIUM_CHARGE 0xd0
#define MSI_EC_BATTERY_MODE_MIN_CHARGE 0xbc
#define MSI_EC_COOLER_BOOST_ADDRESS 0x98
#define MSI_EC_COOLER_BOOST_ON 0x82
#define MSI_EC_COOLER_BOOST_OFF 0x02
#define MSI_EC_SHIFT_MODE_ADDRESS 0xf2
#define MSI_EC_SHIFT_MODE_TURBO 0xc4
#define MSI_EC_SHIFT_MODE_SPORT 0xc0
#define MSI_EC_SHIFT_MODE_COMFORT 0xc1
#define MSI_EC_SHIFT_MODE_ECO 0xc2
#define MSI_EC_SHIFT_MODE_OFF 0x80
#define MSI_EC_FW_VERSION_ADDRESS 0xa0
#define MSI_EC_FW_VERSION_LENGTH 12
#define MSI_EC_FW_DATE_ADDRESS 0xac
#define MSI_EC_FW_DATE_LENGTH 8
#define MSI_EC_FW_TIME_ADDRESS 0xb4
#define MSI_EC_FW_TIME_LENGTH 8
#define MSI_EC_CHARGE_CONTROL_ADDRESS 0xef
#define MSI_EC_CHARGE_CONTROL_OFFSET_START 0x8a
#define MSI_EC_CHARGE_CONTROL_OFFSET_END 0x80
#define MSI_EC_CHARGE_CONTROL_RANGE_MIN 0x8a
#define MSI_EC_CHARGE_CONTROL_RANGE_MAX 0xe4
#define MSI_EC_CPU_REALTIME_TEMPERATURE 0x68
#define MSI_EC_CPU_REALTIME_FAN_SPEED 0x71
#define MSI_EC_GPU_REALTIME_TEMPERATURE 0x80
#define MSI_EC_GPU_REALTIME_FAN_SPEED 0x89

#endif // __MSI_EC_CONSTANTS__
