name: Bug report
description: Report a bug
labels: ["bug"]
title: "[BUG] "

body:
  - type: markdown
    attributes:
      value: >
        **том Please add model name, EC version and short description to Issue title тон**

  - type: markdown
    attributes:
      value: >
        > [!IMPORTANT]
        
        > Check the [supported devices list](https://github.com/BeardOverflow/msi-ec/discussions/277) **BEFORE** opening new Issue.
        
        >
        
        > If you see your device in supported list, but driver reports that it unsupported -
        **write about this problem to last issue related to your device, which is linked in [device list](https://github.com/BeardOverflow/msi-ec/discussions/277).**
        
        >
        
        > If you see `Your firmware version is not supported!` when loading module - your version is not supported.
        Check issues related to your device via search, in [device list](https://github.com/BeardOverflow/msi-ec/discussions/277).
        Use [Support request Issue template](https://github.com/BeardOverflow/msi-ec/issues/new?template=support_request.yml)
        if you have not found any older issues related to your device.


  - type: input
    id: model
    attributes:
      label: Laptop model
      description: Please provide full model name
      placeholder: "Example: [MSI] Summit E14 Flip Evo A13MT"
    validations:
      required: true

  - type: checkboxes
    id: proof
    attributes:
      label: Confirmation
      options:
        - label: >
            I'm confirming that EC version is supported in the [supported devices list](https://github.com/BeardOverflow/msi-ec/discussions/277) or in my fork. 
            In other case use [Support Request template](https://github.com/BeardOverflow/msi-ec/issues/new?template=support_request.yml)
          required: true

  - type: input
    id: ec-firmware
    attributes:
      label: EC firmware version
      description: |
        + `cat /sys/devices/platform/msi-ec/fw_version`
        + `sudo modprobe ec_sys` and `sudo strings /sys/kernel/debug/ec/ec0/io` and copy string which looks like example
      placeholder: "Example: 14JKEMS1.1041024202210:53:30"
    validations:
      required: false

  - type: input
    id: distro
    attributes:
      label: Distro name and version
      placeholder: "Example: Arch Linux From Scratch, version 101"
    validations:
      required: true

  - type: input
    id: kernel
    attributes:
      label: Kernel version
      description: "To get kernel version run: `uname -r`"
      placeholder: "Example: 6.16.0-arch1-1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue
    validations:
      required: false
