name: New firmware request
description: Request to add support for a new device (new EC configuration)
labels: [ "New firmware" ]
title: "[Support request] "

body:
  - type: markdown
    attributes:
      value: >
        **том Please add model name and EC version to Issue title тон**

  - type: markdown
    attributes:
      value: >
        > [!IMPORTANT]
        
        > Check the [supported devices list](https://github.com/BeardOverflow/msi-ec/discussions/277) **BEFORE** opening new Issue.
        
        >
        
        > If you see your device as supported, but driver reports that it unsupported - check last links/issues 
        for your device name or EC version (preferred) and write your problem there **WITHOUT** opening new Issue.
        
        >
        
        > If your device is not supported at all, please answer next questions about your device
        and attach EC dump. Additionally you can try to analyze App features using
        [Support Guide](https://github.com/BeardOverflow/msi-ec/blob/main/docs/device_support_guide.md).

  - type: markdown
    attributes:
      value: >
        > [!TIP]
        
        > It's also possible to skip the issue and make a pull request directly, but please provide an EC dump.

  - type: input
    id: model
    attributes:
      label: Laptop model
      description: Please provide full model name. You can skip writing MSI
      placeholder: "Example: [MSI] Summit E14 Flip Evo A13MT"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Please provide EC dump in text form using one of next methods:
        + [MSI-EC Debug mode](https://github.com/BeardOverflow/msi-ec/blob/main/docs/device_support_guide.md#msi-ec-debug-mode)
        + [EC-SYS driver](https://github.com/BeardOverflow/msi-ec/blob/main/docs/device_support_guide.md#ec-sys-method)
        + [RW Everything](https://github.com/BeardOverflow/msi-ec/blob/main/docs/device_support_guide.md#windows-method-recommended) on Windows (share text from save file)
        + [YAMDCC](https://github.com/Sparronator9999/YAMDCC/wiki/How-to-make-a-config-for-YAMDCC#manually-based-on-other-config) on Windows
        
        If you have found definitions for some addresses - paste them to [Additional context](#additional-context).
        
        > [!NOTE]
        > Don't be confused with BIOS and EC versions:
        >
        > EC example: `****EMS1.101` or `****IMS1.101`
        >
        > BIOS example: `E****IMS.101` or `E****AMS.101`

  - type: input
    id: ec-firmware
    attributes:
      label: EC firmware version
      placeholder: "Example: ****EMS1.101 or ****IMS1.101"
    validations:
      required: true

  - type: textarea
    id: ec-dump
    attributes:
      label: EC Dump
      description: >
        Please provide EC dump in text form **ONLY** (save dump and paste its text). Attached files might be ignored.
      render: text
    validations:
      required: true

  - type: input
    id: bios-version
    attributes:
      label: BIOS version
      description: >
        Starts from `E` and looks like `E****IMS.101` or `E****AMS.101`.
      placeholder: "Example: E****IMS.101 or E****AMS.101"
    validations:
      required: false

  - type: dropdown
    id: gpu
    attributes:
      label: GPU
      description: Your GPU
      options:
        - Nvidia
        - AMD
        - Intel Arc (as dGPU)
        - iGPU only (Intel)
        - iGPU only (AMD)
    validations:
      required: true

  - type: dropdown
    id: fans
    attributes:
      label: Number of fans
      description: How many fans does your laptop have?
      options:
        - No answer / I don't know
        - 1 fan
        - 2 fans
        - 3 fans
        - 4 fans
        - Fanless
    validations:
      required: true

  - type: checkboxes
    id: webcam
    attributes:
      label: Webcam block
      description: >
        Select one or few options about Webcam block:
      options:
        - label: No webcam
        - label: Slider (small thing that covers the camera)
        - label: Camera Button (often on F6 key)
        - label: Camera Toggle Switch (often on the side of case)
        - label: Camera switch in MSI App

  - type: dropdown
    id: rgb-keyboard
    attributes:
      label: Keyboard backlight type
      description: Does your keyboard support multi color RGB backlight?
      options:
        - Single color
        - RGB
        - No backlight
    validations:
      required: true

  - type: dropdown
    id: fn-win
    attributes:
      label: Win and FN button location
      description: Where is the FN key located on your keyboard relatively to Win
      options:
        - No answer
        - The FN key is on the left side of the Win key
        - The FN key is on the right side of the Win key
    validations:
      required: true

  - type: checkboxes
    id: speaker-mic-led
    attributes:
      label: Mic and Speaker mute LED
      description: |
        Does your keyboard have small leds on the speaker and mic mute buttons?
        They are usually found on F1 and F5 keys
      options:
        - label: Speaker mute led
        - label: Mic mute led
        - label: No leds / no mute buttons

  - type: input
    id: distribution
    attributes:
      label: Distro name and version
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other info you want to provide
    validations:
      required: false
