name: New firmware request
description: Request to add support for a new device (new EC configuration)
labels: ["New firmware"]

body:
  - type: markdown
    attributes:
      value: >
        Before you open a new issue, please check the [supported devices list](https://github.com/BeardOverflow/msi-ec/discussions/277),
        If it's not there, you should follow the guide mentioned on the main page,
        and then make a list of the addresses for features and their values to submit it here.
        
        It's also possible to skip the issue and make a pull request directly, but please provide an EC dump.

  - type: input
    id: model
    attributes:
      label: Laptop model
      description: Your laptop model
    validations:
      required: true

    - type: input
    id: distribution
    attributes:
      label: What distribution do you use?
      description: Don't forget to add the version if there is one.
    validations:
      required: true

- type: input
    id: bios-version
    attributes:
      label: BIOS version
      description: On linux: copy and paste the output of (cat /sys/class/dmi/id/bios_version),
      or get it from the info page in the bios.
    validations:
      required: false

  - type: input
    id: ec-firmware
    attributes:
      label: EC firmware version
      description: Get your current EC firmware version from the msi app on windows or the info page in the bios.
    validations:
      required: false

  - type: textarea
    id: feature-list
    attributes:
      label: List of addresses and their values
      description: Provide an ec dump by following any of the linux methods in the guide,
      you can also mention the address of each feature and possible values.
      render: text
    validations:
      required: false

  - type: dropdown
    id: gpu
    attributes:
      label: GPU
      description: Your GPU
      options:
        - Nvidia
        - AMD
        - iGPU only (Intel)
        - iGPU only (AMD)
    validations:
      required: true

  - type: dropdown
    id: fans
    attributes:
      label: How many fans does your laptop have?
      description: most laptops with 1 GPU have only one fan.
      options:
        - 1 fan
        - 2 fans
        - More than 2
        - I don't know
        - Other (please mention in the end)
    validations:
      required: true

  - type: dropdown
    id: webcam
    attributes:
      label: How do you block the webcam?
      description: Some laptops have webcams that can be blocked physically (slider), while others use software to block it (no slider).
      options:
        - Slider (small thing that covers the camera)
        - No slider (camera is blocked using the msi app on windows)
        - No webcam
        - Other (please mention in the end)
    validations:
      required: true

  - type: dropdown
    id: rgb-keyboard
    attributes:
      label: Is your keyboard RGB?
      description: Does your keyboard support multi color RGB backlight?
      options:
        - No (single color)
        - Yes (multi color RGB)
        - No backlight
    validations:
      required: true

  - type: dropdown
    id: speaker-mic-led
    attributes:
      label: Mic and Speaker mute LED
      description: Does your keyboard have small leds on the mute buttons for speaker and mic?
      usually found on F1 and F5 keys
      options:
        - No leds / no mute buttons
        - Only 1 (for mic mute)
        - Only 1 (for speaker mute)
        - 2 LEDs (mic and speaker)
        - I don't know
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other info you want to provide
    validations:
      required: false
