name: New firmware request
description: Request to add support for a new device (new EC configuration)
labels: ["New firmware"]

body:
  - type: markdown
    attributes:
      value: >
        Before you open a new issue, please check the [supported devices list](https://github.com/BeardOverflow/msi-ec/blob/main/docs/supported_devices.md),
        If it's not there, you should follow the guide mentioned on the main page,
        and then make a list of the addresses for features and their values to submit it here.
        
        It's also possible to skip the issue and make a pull request directly.

  - type: input
    id: model
    attributes:
      label: Laptop model
      description: Your laptop model
    validations:
      required: true

  - type: input
    id: ec-firmware
    attributes:
      label: EC firmware version
      description: Get your current EC firmware version from the msi app on windows or the info page in the bios
    validations:
      required: false

  - type: textarea
    id: feature-list
    attributes:
      label: List of addresses and their values
      description: Make a list of address = value for each possible feature, you can submit an incomplete list and continue later
      render: text
    validations:
      required: false

  - type: dropdown
    id: gpu
    attributes:
      label: GPU
      description: Your GPU
      options:
        - Nvidia
        - AMD
        - iGPU only (Intel)
        - iGPU only (AMD)
    validations:
      required: true

  - type: dropdown
    id: rgb-keyboard
    attributes:
      label: Is your keyboard RGB?
      description: Does your keyboard support multi color RGB backlight?
      options:
        - No (single color)
        - Yes (multi color RGB)
        - No backlight
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other info you want to provide
    validations:
      required: false
