name: COPR Build - Release

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    # On vérifie que le tag est bien sur la branche main
    if: github.ref_type == 'tag' && github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: "Change version"
        run: "sed -i 's/^VERSION :=.*/VERSION := ${{ github.ref_name }}/' Makefile.vars"
    
      - name: "Displaying makefile.vars"
        run: "cat Makefile.vars"
      
      - name: "Committing new version"
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"=

          git add Makefile.vars
          git commit -m "chore: bump version to $NEW_VERSION in makefile.vars [skip ci]"
          git push origin main
      
      - name: "Waiting for github indexing"
        run: sleep 20
      
      - name: "Triggering COPR build"
        run: |
          curl -X POST "${{ secrets.COPR_WEBHOOK_URL }}"