name: COPR Build - Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Change version"
        run: "sed -i 's/^VERSION :=.*/VERSION := ${{ github.ref_name }}/' Makefile.vars"
    
      - name: "Displaying makefile.vars"
        run: "cat Makefile.vars"
      
      - name: "Committing new version"
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"=

          git add Makefile.vars
          git commit -m "chore: bump version to $NEW_VERSION in makefile.vars [skip ci]"
          git push origin main
      
      - name: "Waiting for github indexing"
        run: sleep 20
      
      - name: "Triggering COPR build"
        run: |
          PROJECT_ID="223651"
          PKG_NAME="msi-ec-kmod"
          UUID="${{ secrets.COPR_UUID }}"
          
          URL="https://copr.fedorainfracloud.org/webhooks/custom/${PROJECT_ID}/${UUID}/${PKG_NAME}/"
          
          echo "Starting build."
          curl -Ssi -X POST "$URL"