name: COPR Build - Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Triggering COPR build"
        run: |
          PROJECT_ID="223651"
          PKG_NAME="msi-ec-kmod"
          UUID="${{ secrets.COPR_UUID }}"
          
          URL="https://copr.fedorainfracloud.org/webhooks/custom/${PROJECT_ID}/${UUID}/${PKG_NAME}/"
          
          echo "Starting build."
          curl -Ssi -X POST "$URL"